#!/bin/bash

file=$1

hash1=`md5sum $file | cut -d ' ' -f 1`
hash2=`md5sum ./server/$file | cut -d ' ' -f 1`


echo "Hash do arquivo do cliente: $hash1"
echo "Hash do arquivo no server:  $hash2"

if [ $hash1 == $hash2 ]
then
  echo "Sao iguais"

else
  echo "Sao diferentes"
fi
